name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Build and Run Java App with MongoDB
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Docker network and MongoDB
        run: |
          docker network create --driver bridge se-methods
          docker pull mongo
          docker run -d --name mongo-dbserver --network se-methods mongo

      - name: Build fat JAR with dependencies
        run: mvn clean compile assembly:single

      - name: Show files in target/ (debug step)
        run: ls -lh target/

      - name: Build Docker image
        run: docker build -t se_methods .

      - name: Run Docker container
        run: docker run --network se-methods --name devopscontainer se_methods

      - name: View container logs
        run: docker logs devopscontainer

